version: '3.1'

services:

  wordpress:
    image: wordpress:6.3
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PASSWORD: meetup
      WORDPRESS_DB_NAME: dersdbadi
  wpcli:
    image: wordpress:cli
    volumes:
      - .:/var/www/html
    command: sh -c "sleep 20 && wp core install --path=/var/www/html --url=localhost --title=meetupistanbul --admin_user=meetupistanbul --admin_password=meetupistanbul --admin_email=tolgakaprol@gmail.com"
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - ./data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: meetup
      MYSQL_DATABASE: dersdbadi
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 85:80
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: meetup
